spring.application.name=${SPRING_APPLICATION_NAME:Summor-War}

server.port=${PORT:8080}

sw.server=${SW_SERVER:asia}

selenium.headless=${SELENIUM_HEADLESS:true}

redeem.sleep-between-accounts-ms=${REDEEM_SLEEP_BETWEEN_ACCOUNTS_MS:10000}
